# Results

--- DeBERTa Model Performance ---

Aspect Extraction Accuracy: 0.4547

Sentiment Accuracy (conditional on correct aspect): 0.6655

--- Basic T5 Model Performance ---

Aspect Extraction Accuracy: 0.0000

Sentiment Accuracy (conditional on correct aspect): 0.0000

--- Fine Tuned T5 Model Performance ---

Aspect Extraction Accuracy: 0.5422

Sentiment Accuracy (conditional on correct aspect): 0.6006

## Best Model would be the Fine Tuned T5 model

# Create a Test Dataset
Semeval does not contains the ground truth for the test set, the ground truth will be determine via LLM. First labeling was done via Microsoft copilot and validated by Qwen.

In [ ]:
from datasets import load_dataset

ds = load_dataset("tomaarsen/setfit-absa-semeval-laptops")
dataset = ds['test']

print(f"New training dataset size: {len(dataset)}")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/117k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/30.2k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/2358 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/654 [00:00<?, ? examples/s]

New training dataset size: 654

In [ ]:
import json

output_file_name = 'dataset_text_labels.json'

# Prepare data for JSON dump
processed_data = []
for item in dataset:
    processed_data.append({
        'text': item['text'],
        'span': item['span'],
        'label': item['label']
    })

# Dump to JSON file
with open(output_file_name, 'w') as f:
    json.dump(processed_data, f, indent=4)

print(f"Successfully dumped {len(processed_data)} items to {output_file_name}")

Successfully dumped 654 items to dataset_text_labels.json

# Fine Tuning Deberata for ABSA

In [ ]:
%%capture
!pip install transformers datasets accelerate evaluate seqeval torch

In [ ]:
model_name = "microsoft/deberta-v3-base"

label_list = [
    "O",
    "B-POS", "I-POS",
    "B-NEU", "I-NEU",
    "B-NEG", "I-NEG",
]

label_to_id = {label: i for i, label in enumerate(label_list)}
id_to_label = {i: label for i, label in enumerate(label_list)}

In [ ]:
from datasets import load_dataset

ds = load_dataset("tomaarsen/setfit-absa-semeval-laptops")
dataset = ds["train"].train_test_split(test_size=0.2, seed=42)

train_dataset = dataset['train']
test_dataset = dataset['test']

print(f"New training dataset size: {len(train_dataset)}")
print(f"Validation dataset size: {len(test_dataset)}")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/117k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/30.2k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/2358 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/654 [00:00<?, ? examples/s]

New training dataset size: 1886
Validation dataset size: 472

## Data Prep

In [ ]:
train_dataset[0]

{'text': "Whenever I call Dell about an unrelated problem, they ask me if my laptop is running slowly and if I'd like to purchase more memory for $75.",
 'span': 'memory',
 'label': 'neutral',
 'ordinal': 0}

In [ ]:
from huggingface_hub import notebook_login
# pw = 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
notebook_login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [ ]:
import numpy as np
import string

def prepare_absa_data(ds):
    text_no_punct = ds['text'].translate(str.maketrans('', '', string.punctuation))
    span_no_punct = ds['span'].translate(str.maketrans('', '', string.punctuation))
    tokens = text_no_punct.split()
    span_tokens = span_no_punct.split()
    tags = [label_to_id['O']] * len(tokens)

    sentiment_label = ds['label'].upper()
    b_tag_key = f'B-{sentiment_label[:3]}'
    i_tag_key = f'I-{sentiment_label[:3]}'

    b_tag = label_to_id.get(b_tag_key, label_to_id['O'])
    i_tag = label_to_id.get(i_tag_key, label_to_id['O'])

    for i in range(len(tokens) - len(span_tokens) + 1):
        if tokens[i:i + len(span_tokens)] == span_tokens:
            tags[i] = b_tag
            for j in range(i + 1, i + len(span_tokens)):
                tags[j] = i_tag
            break

    return {"tokens": tokens, "tags": tags}

processed_train_dataset = train_dataset.map(prepare_absa_data, batched=False)
processed_test_dataset = test_dataset.map(prepare_absa_data, batched=False)

Map:   0%|          | 0/1886 [00:00<?, ? examples/s]

Map:   0%|          | 0/472 [00:00<?, ? examples/s]

In [ ]:
from transformers import DebertaV2Tokenizer

tokenizer = DebertaV2Tokenizer.from_pretrained("microsoft/deberta-v3-base")

def tokenize_and_align_labels(ds):
    tokenized_inputs = tokenizer(
        ds["tokens"],
        truncation=True,
        is_split_into_words=True
    )

    all_labels = []

    for i, labels in enumerate(ds["tags"]):
        word_ids = tokenized_inputs.word_ids(batch_index=i)
        previous_word_idx = None
        label_ids = []

        for word_idx in word_ids:
            if word_idx is None:
                # Special tokens ([CLS], [SEP], padding) get -100 (ignored in loss)
                label_ids.append(-100)
            elif word_idx != previous_word_idx:
                # First token of a word gets the actual label
                label_ids.append(labels[word_idx])
            else:
                # Subsequent tokens of a word get -100
                label_ids.append(-100)

            previous_word_idx = word_idx
        all_labels.append(label_ids)

    tokenized_inputs["labels"] = all_labels
    return tokenized_inputs

tokenized_dataset = processed_train_dataset.map(tokenize_and_align_labels, batched=True)
tokenized_test = processed_test_dataset.map(tokenize_and_align_labels, batched=True)

tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

spm.model:   0%|          | 0.00/2.46M [00:00<?, ?B/s]

Map:   0%|          | 0/1886 [00:00<?, ? examples/s]

Map:   0%|          | 0/472 [00:00<?, ? examples/s]

In [ ]:
tokenized_dataset = tokenized_dataset.remove_columns(['text', 'span', 'label', 'ordinal', 'tokens', 'tags'])
tokenized_test = tokenized_test.remove_columns(['text', 'span', 'label', 'ordinal', 'tokens', 'tags'])

## Model Metrics

In [ ]:
import evaluate

metric = evaluate.load("seqeval")

def compute_metrics(p):
    predictions, labels = p
    predictions = np.argmax(predictions, axis=2)

    true_predictions = [
        [label_list[p] for (p, l) in zip(prediction, label) if l != -100]
        for prediction, label in zip(predictions, labels)
    ]
    true_labels = [
        [label_list[l] for (p, l) in zip(prediction, label) if l != -100]
        for prediction, label in zip(predictions, labels)
    ]

    results = metric.compute(predictions=true_predictions, references=true_labels)

    # Return flat metrics for logging
    return {
        "precision": results["overall_precision"],
        "recall": results["overall_recall"],
        "f1": results["overall_f1"],
        "accuracy": results["overall_accuracy"],
    }

Downloading builder script: 0.00B [00:00, ?B/s]

## Model Training

In [ ]:
from torch import nn
from transformers import Trainer
import torch

class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.pop("labels").long()
        outputs = model(**inputs)
        logits = outputs.logits

        class_weights = torch.tensor(
            [1.0, 4.0, 6.0, 4.0, 6.0, 4.0, 6.0],
            device=logits.device,
            dtype=torch.float32
        )
        loss_fn = nn.CrossEntropyLoss(weight=class_weights, ignore_index=-100)
        loss = loss_fn(logits.view(-1, self.model.config.num_labels), labels.view(-1))
        return (loss, outputs) if return_outputs else loss

In [ ]:
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from transformers import (
    DebertaV2ForTokenClassification,
    DataCollatorForTokenClassification
)

num_labels = len(label_list)

model = DebertaV2ForTokenClassification.from_pretrained(
    "microsoft/deberta-v3-base",
    num_labels=num_labels,
    id2label=id_to_label,
    label2id=label_to_id,
    torch_dtype=torch.float32
)

data_collator = DataCollatorForTokenClassification(tokenizer=tokenizer)

config.json:   0%|          | 0.00/579 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/371M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/371M [00:00<?, ?B/s]

DebertaV2ForTokenClassification LOAD REPORT from: microsoft/deberta-v3-base
Key                                     | Status     |
----------------------------------------+------------+-
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |
mask_predictions.dense.weight           | UNEXPECTED |
lm_predictions.lm_head.dense.weight     | UNEXPECTED |
lm_predictions.lm_head.dense.bias       | UNEXPECTED |
mask_predictions.dense.bias             | UNEXPECTED |
mask_predictions.classifier.weight      | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |
mask_predictions.LayerNorm.bias         | UNEXPECTED |
lm_predictions.lm_head.bias             | UNEXPECTED |
mask_predictions.classifier.bias        | UNEXPECTED |
mask_predictions.LayerNorm.weight       | UNEXPECTED |
classifier.bias                         | MISSING    |
classifier.weight                       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir="./deberta-absa",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=15,
    weight_decay=0.01,
    warmup_steps=117,
    eval_strategy="epoch",
    save_strategy="no",
    logging_steps=1,
    logging_strategy="steps",
    load_best_model_at_end=False,
    fp16=False,
    metric_for_best_model="f1",
    push_to_hub=False,
    report_to="none",
)

trainer = WeightedTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset,
    eval_dataset=tokenized_test,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

trainer.train()

/usr/local/lib/python3.12/dist-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

TrainOutput(global_step=1770, training_loss=0.521762723547254, metrics={'train_runtime': 451.6011, 'train_samples_per_second': 62.644, 'train_steps_per_second': 3.919, 'total_flos': 644450624662716.0, 'train_loss': 0.521762723547254, 'epoch': 15.0})

In [ ]:
model.push_to_hub(repo_id="whismyswift/deberta-absa")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...twj4wfr/model.safetensors:   0%|          |  553kB /  735MB

CommitInfo(commit_url='https://huggingface.co/whismyswift/deberta-absa/commit/6492777f7dd61b52fa3cc825394b183acaef9a00', commit_message='Upload DebertaV2ForTokenClassification', commit_description='', oid='6492777f7dd61b52fa3cc825394b183acaef9a00', pr_url=None, repo_url=RepoUrl('https://huggingface.co/whismyswift/deberta-absa', endpoint='https://huggingface.co', repo_type='model', repo_id='whismyswift/deberta-absa'), pr_revision=None, pr_num=None)

In [ ]:
tokenizer.push_to_hub(repo_id="whismyswift/deberta-absa")

CommitInfo(commit_url='https://huggingface.co/whismyswift/deberta-absa/commit/eea69e011691f47a567da69a74731a8f647b92df', commit_message='Upload tokenizer', commit_description='', oid='eea69e011691f47a567da69a74731a8f647b92df', pr_url=None, repo_url=RepoUrl('https://huggingface.co/whismyswift/deberta-absa', endpoint='https://huggingface.co', repo_type='model', repo_id='whismyswift/deberta-absa'), pr_revision=None, pr_num=None)

## Inference

In [1]:
import json

file_name = 'dataset_text_labels.json'

with open(file_name, 'r') as f:
    dataset = json.load(f)

print(f"Successfully loaded {len(dataset)} items")

Successfully loaded 651 items

In [3]:
import torch
from transformers import AutoTokenizer, AutoModelForTokenClassification

tokenizer = AutoTokenizer.from_pretrained("whismyswift/deberta-absa")
model = AutoModelForTokenClassification.from_pretrained("whismyswift/deberta-absa")
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

DebertaV2ForTokenClassification(
  (deberta): DebertaV2Model(
    (embeddings): DebertaV2Embeddings(
      (word_embeddings): Embedding(128100, 768, padding_idx=0)
      (LayerNorm): LayerNorm((768,), eps=1e-07, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): DebertaV2Encoder(
      (layer): ModuleList(
        (0-11): 12 x DebertaV2Layer(
          (attention): DebertaV2Attention(
            (self): DisentangledSelfAttention(
              (query_proj): Linear(in_features=768, out_features=768, bias=True)
              (key_proj): Linear(in_features=768, out_features=768, bias=True)
              (value_proj): Linear(in_features=768, out_features=768, bias=True)
              (pos_dropout): Dropout(p=0.1, inplace=False)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): DebertaV2SelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-07, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): DebertaV2Intermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): DebertaV2Output(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-07, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (rel_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-07, elementwise_affine=True)
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=7, bias=True)
)

In [4]:
def deberta_predict_aspect_sentiment(text, model, tokenizer, label_list, device):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, is_split_into_words=False).to(device)

    with torch.no_grad():
        logits = model(**inputs).logits

    predictions = torch.argmax(logits, dim=2)
    predicted_token_ids = predictions[0].cpu().numpy()

    tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0])
    word_ids = inputs.word_ids(batch_index=0)

    predicted_labels = [label_list[t] for t in predicted_token_ids]

    # Reconstruct words and align labels for original words
    aligned_words_with_labels = []
    current_word = ""
    current_label_sequence = []
    previous_word_id = None

    for i, word_id in enumerate(word_ids):
        if word_id is None: # Special tokens like CLS, SEP
            continue
        if previous_word_id != word_id: # New word detected
            if current_word: # Store the previous word and its label
                # Simplified label assignment: take the first non-O label for the word
                final_label = "O"
                for lab in current_label_sequence:
                    if lab != "O":
                        final_label = lab
                        break
                aligned_words_with_labels.append((current_word.replace(' ', ''), final_label))
            current_word = tokens[i]
            current_label_sequence = [predicted_labels[i]]
        else: # Continuation of the same word
            current_word += tokens[i].replace(' ', '') # Append sub-token, remove ' ' prefix
            current_label_sequence.append(predicted_labels[i])
        previous_word_id = word_id

    # Add the last word
    if current_word:
        final_label = "O"
        for lab in current_label_sequence:
            if lab != "O":
                final_label = lab
                break
        aligned_words_with_labels.append((current_word.replace(' ', ''), final_label))


    # Extract aspects and sentiments from aligned words using BIO tagging
    extracted_aspect_sentiments = []
    current_aspect_span_words = []
    current_span_sentiment = None

    for word, label in aligned_words_with_labels:
        if label.startswith('B-'):
            if current_aspect_span_words: # Save previous aspect if any
                extracted_aspect_sentiments.append({
                    "aspect": " ".join(current_aspect_span_words),
                    "sentiment": current_span_sentiment
                })
            current_aspect_span_words = [word]
            current_span_sentiment = label[2:] # e.g., 'POS', 'NEU', 'NEG'
        elif label.startswith('I-'):
            if current_aspect_span_words and current_span_sentiment == label[2:]: # Continue current span
                current_aspect_span_words.append(word)
            else: # I-tag without preceding B-tag, or sentiment mismatch, treat as new B-tag
                if current_aspect_span_words:
                    extracted_aspect_sentiments.append({
                        "aspect": " ".join(current_aspect_span_words),
                        "sentiment": current_span_sentiment
                    })
                current_aspect_span_words = [word]
                current_span_sentiment = label[2:]
        else: # 'O' tag
            if current_aspect_span_words: # Save previous aspect if any
                extracted_aspect_sentiments.append({
                    "aspect": " ".join(current_aspect_span_words),
                    "sentiment": current_span_sentiment
                })
                current_aspect_span_words = []
                current_span_sentiment = None

    if current_aspect_span_words: # Add the last aspect if any
        extracted_aspect_sentiments.append({
            "aspect": " ".join(current_aspect_span_words),
            "sentiment": current_span_sentiment
        })

    return extracted_aspect_sentiments

In [5]:
import torch
from tqdm.auto import tqdm
import json

label_list = [
    "O",
    "B-POS", "I-POS",
    "B-NEU", "I-NEU",
    "B-NEG", "I-NEG",
]

deberta_predictions_on_test_set = []

for item in tqdm(dataset, desc="Predicting with DeBERTa"):
    text = item['text']
    original_span = item['span']
    original_label = item['label']

    predicted_aspect_sentiments = deberta_predict_aspect_sentiment(
        text,
        model,
        tokenizer,
        label_list,
        device
    )

    deberta_predictions_on_test_set.append({
        "original_text": text,
        "original_span": original_span,
        "original_label": original_label,
        "predicted_aspect_sentiments": predicted_aspect_sentiments
    })

# Display a few examples
print("\n--- DeBERTa Predictions Examples ---")
for i, pred_item in enumerate(deberta_predictions_on_test_set[:5]):
    print(f"Example {i+1}:")
    print(f"  Text: {pred_item['original_text']}")
    print(f"  Original Span: {pred_item['original_span']}")
    print(f"  Predicted Aspects and Sentiments: {pred_item['predicted_aspect_sentiments']}")
    print("-" * 30)

Predicting with DeBERTa:   0%|          | 0/651 [00:00<?, ?it/s]

--- DeBERTa Predictions Examples ---
Example 1:
  Text: Boot time is super fast, around anywhere from 35 seconds to 1 minute.
  Original Span: Boot time
  Predicted Aspects and Sentiments: [{'aspect': '▁Boot ▁time', 'sentiment': 'POS'}]
------------------------------
Example 2:
  Text: tech support would not fix the problem unless I bought your plan for $150 plus.
  Original Span: tech support
  Predicted Aspects and Sentiments: [{'aspect': '▁tech ▁support', 'sentiment': 'NEG'}]
------------------------------
Example 3:
  Text: Set up was easy.
  Original Span: Set up
  Predicted Aspects and Sentiments: [{'aspect': '▁Set ▁up', 'sentiment': 'POS'}]
------------------------------
Example 4:
  Text: Did not enjoy the new Windows 8 and touchscreen functions.
  Original Span: Windows 8
  Predicted Aspects and Sentiments: [{'aspect': '▁functions.', 'sentiment': 'POS'}]
------------------------------
Example 5:
  Text: Did not enjoy the new Windows 8 and touchscreen functions.
  Original Span: touchscreen functions
  Predicted Aspects and Sentiments: [{'aspect': '▁functions.', 'sentiment': 'POS'}]
------------------------------

In [6]:
correct_aspect_matches_deberta = 0
correct_sentiment_given_aspect_deberta = 0
total_samples_deberta = len(deberta_predictions_on_test_set)

for pred_item in deberta_predictions_on_test_set:
    original_span = pred_item['original_span'].lower()
    original_label = pred_item['original_label'].lower()
    predicted_aspect_sentiments = pred_item['predicted_aspect_sentiments']

    # Check if any predicted aspect matches the original span
    aspect_matched = False
    for predicted_pair in predicted_aspect_sentiments:
        predicted_aspect_text = predicted_pair['aspect'].replace('▁', '').strip().lower()
        predicted_sentiment_text = predicted_pair['sentiment'].lower()

        if predicted_aspect_text == original_span:
            correct_aspect_matches_deberta += 1
            aspect_matched = True
            # If aspect matches, check sentiment
            # Map predicted sentiment abbreviations to full words for comparison
            sentiment_mapping = {
                'pos': 'positive',
                'neg': 'negative',
                'neu': 'neutral'
            }
            mapped_predicted_sentiment = sentiment_mapping.get(predicted_sentiment_text, 'unknown') # Use .get with a default to handle unexpected values

            if mapped_predicted_sentiment == original_label: # Compare mapped predicted sentiment with original label
                correct_sentiment_given_aspect_deberta += 1
            break # Found a match for this original span, move to next item


# Calculate metrics
aspect_accuracy_deberta = correct_aspect_matches_deberta / total_samples_deberta
sentiment_accuracy_deberta = correct_sentiment_given_aspect_deberta / correct_aspect_matches_deberta if correct_aspect_matches_deberta > 0 else 0

print(f"\n--- DeBERTa Model Performance on Test Set ---")
print(f"Total Samples: {total_samples_deberta}")
print(f"Correct Aspect Matches: {correct_aspect_matches_deberta}")
print(f"Aspect Extraction Accuracy: {aspect_accuracy_deberta:.4f}")
print(f"Correct Sentiment (given correct aspect): {correct_sentiment_given_aspect_deberta}")
print(f"Sentiment Accuracy (conditional on correct aspect): {sentiment_accuracy_deberta:.4f}")

--- DeBERTa Model Performance on Test Set ---
Total Samples: 651
Correct Aspect Matches: 296
Aspect Extraction Accuracy: 0.4547
Correct Sentiment (given correct aspect): 197
Sentiment Accuracy (conditional on correct aspect): 0.6655

# Fine Tuning T5 for ABSA

In [ ]:
from huggingface_hub import login
# pw = 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
login(token="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")

In [ ]:
from datasets import load_dataset

ds = load_dataset("tomaarsen/setfit-absa-semeval-laptops")
dataset = ds["train"].train_test_split(test_size=0.2, seed=42)

train_dataset = dataset['train']
test_dataset = dataset['test']

print(f"New training dataset size: {len(train_dataset)}")
print(f"Validation dataset size: {len(test_dataset)}")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/117k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/30.2k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/2358 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/654 [00:00<?, ? examples/s]

New training dataset size: 1886
Validation dataset size: 472

In [ ]:
from transformers import T5TokenizerFast

tokenizer = T5TokenizerFast.from_pretrained("t5-small")

max_input_length = 128
max_target_length = 64

def preprocess_function(examples):
    # New input format: tell the model to extract aspect AND sentiment
    inputs = [f"extract aspect and sentiment: {text}" for text in examples["text"]]

    targets = [f"{span} | {label}" for span, label in zip(examples["span"], examples["label"])]

    model_inputs = tokenizer(inputs, max_length=128, truncation=True)
    labels = tokenizer(targets, max_length=64, truncation=True)  # increased to fit longer targets

    model_inputs["labels"] = [
        [(token if token != tokenizer.pad_token_id else -100) for token in label]
        for label in labels["input_ids"]]

    return model_inputs

tokenized_train_dataset = dataset['train'].map(preprocess_function, batched=True, remove_columns=dataset['train'].column_names)
tokenized_test_dataset = dataset['test'].map(preprocess_function, batched=True, remove_columns=dataset['test'].column_names)

tokenizer_config.json: 0.00B [00:00, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Map:   0%|          | 0/1886 [00:00<?, ? examples/s]

Map:   0%|          | 0/472 [00:00<?, ? examples/s]

In [ ]:
import torch
from transformers import (
    AutoModelForSeq2SeqLM,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer
)

model_name = "t5-small"
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

data_collator = DataCollatorForSeq2Seq(tokenizer, model=model, padding=True)

training_args = Seq2SeqTrainingArguments(
    output_dir="./t5-absa-2",
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy = 'epoch',
    logging_steps=1,
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    weight_decay=0.01,
    save_total_limit=1,
    num_train_epochs=15,
    predict_with_generate=True,
    fp16=torch.cuda.is_available(),
    push_to_hub=False,
    report_to="none",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train_dataset,
    eval_dataset=tokenized_test_dataset,
    processing_class=tokenizer,
    data_collator=data_collator,
)

trainer.train()

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/131 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['encoder.embed_tokens.weight', 'decoder.embed_tokens.weight', 'lm_head.weight'].

TrainOutput(global_step=1770, training_loss=1.082689602092161, metrics={'train_runtime': 241.8833, 'train_samples_per_second': 116.957, 'train_steps_per_second': 7.318, 'total_flos': 459629745340416.0, 'train_loss': 1.082689602092161, 'epoch': 15.0})

In [ ]:
trainer.push_to_hub()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...-absa-2/model.safetensors:   0%|          |  553kB /  242MB

  ...-absa-2/training_args.bin:   1%|1         |  74.0B / 5.33kB

CommitInfo(commit_url='https://huggingface.co/whismyswift/t5-absa-2/commit/73ab3b5afb4ce86495178d2a8d143f00026c3e23', commit_message='End of training', commit_description='', oid='73ab3b5afb4ce86495178d2a8d143f00026c3e23', pr_url=None, repo_url=RepoUrl('https://huggingface.co/whismyswift/t5-absa-2', endpoint='https://huggingface.co', repo_type='model', repo_id='whismyswift/t5-absa-2'), pr_revision=None, pr_num=None)

## Inference

In [ ]:
import json

file_name = 'dataset_text_labels.json'

with open(file_name, 'r') as f:
    dataset = json.load(f)

print(f"Successfully loaded {len(dataset)} items")

Successfully loaded 651 items

In [ ]:
dataset

[{'text': 'Boot time is super fast, around anywhere from 35 seconds to 1 minute.',
  'span': 'Boot time',
  'label': 'positive'},
 {'text': 'tech support would not fix the problem unless I bought your plan for $150 plus.',
  'span': 'tech support',
  'label': 'negative'},
 {'text': 'Set up was easy.', 'span': 'Set up', 'label': 'positive'},
 {'text': 'Did not enjoy the new Windows 8 and touchscreen functions.',
  'span': 'Windows 8',
  'label': 'negative'},
 {'text': 'Did not enjoy the new Windows 8 and touchscreen functions.',
  'span': 'touchscreen functions',
  'label': 'negative'},
 {'text': "Other than not being a fan of click pads (industry standard these days) and the lousy internal speakers, it's hard for me to find things about this notebook I don't like, especially considering the $350 price tag.",
  'span': 'internal speakers',
  'label': 'negative'},
 {'text': "Other than not being a fan of click pads (industry standard these days) and the lousy internal speakers, it's hard for me to find things about this notebook I don't like, especially considering the $350 price tag.",
  'span': 'price tag',
  'label': 'positive'},
 {'text': "Other than not being a fan of click pads (industry standard these days) and the lousy internal speakers, it's hard for me to find things about this notebook I don't like, especially considering the $350 price tag.",
  'span': 'click pads',
  'label': 'negative'},
 {'text': 'No installation disk (DVD) is included.',
  'span': 'installation disk (DVD)',
  'label': 'negative'},
 {'text': "It's fast, light, and simple to use.",
  'span': 'use',
  'label': 'positive'},
 {'text': 'Works well, and I am extremely happy to be back to an apple OS.',
  'span': 'Works',
  'label': 'positive'},
 {'text': 'Works well, and I am extremely happy to be back to an apple OS.',
  'span': 'apple OS',
  'label': 'positive'},
 {'text': "Sure it's not light and slim but the features make up for it 100%.",
  'span': 'features',
  'label': 'positive'},
 {'text': 'I am pleased with the fast log on, speedy WiFi connection and the long battery life (>6 hrs).',
  'span': 'log on',
  'label': 'positive'},
 {'text': 'I am pleased with the fast log on, speedy WiFi connection and the long battery life (>6 hrs).',
  'span': 'WiFi connection',
  'label': 'positive'},
 {'text': 'I am pleased with the fast log on, speedy WiFi connection and the long battery life (>6 hrs).',
  'span': 'battery life',
  'label': 'positive'},
 {'text': 'The Apple engineers have not yet discovered the delete key.',
  'span': 'delete key',
  'label': 'negative'},
 {'text': 'Made interneting (part of my business) very difficult to maintain.',
  'span': 'interneting',
  'label': 'negative'},
 {'text': 'Luckily, for all of us contemplating the decision, the Mac Mini is priced just right.',
  'span': 'priced',
  'label': 'positive'},
 {'text': 'Super light, super sexy and everything just works.',
  'span': 'works',
  'label': 'positive'},
 {'text': 'Only problem that I had was that the track pad was not very good for me, I only had a problem once or twice with it, But probably my computer was a bit defective.',
  'span': 'track pad',
  'label': 'negative'},
 {'text': 'It is super fast and has outstanding graphics.',
  'span': 'graphics',
  'label': 'positive'},
 {'text': 'But the mountain lion is just too slow.',
  'span': 'mountain lion',
  'label': 'negative'},
 {'text': 'Strong build though which really adds to its durability.',
  'span': 'durability',
  'label': 'positive'},
 {'text': 'Strong build though which really adds to its durability.',
  'span': 'build',
  'label': 'positive'},
 {'text': 'The battery life is excellent- 6-7 hours without charging.',
  'span': 'battery life',
  'label': 'positive'},
 {'text': "I've had my computer for 2 weeks already and it works perfectly.",
  'span': 'works',
  'label': 'positive'},
 {'text': 'And I may be the only one but I am really liking Windows 8.',
  'span': 'Windows 8',
  'label': 'positive'},
 {'text': 'The baterry is very longer.',
  'span': 'baterry',
  'label': 'positive'},
 {'text': 'Its size is ideal and the weight is acceptable.',
  'span': 'size',
  'label': 'positive'},
 {'text': 'Its size is ideal and the weight is acceptable.',
  'span': 'weight',
  'label': 'positive'},
 {'text': 'I can say that I am fully satisfied with the performance that the computer has supplied.',
  'span': 'performance',
  'label': 'positive'},
 {'text': 'This laptop has only 2 USB ports, and they are both on the same side.',
  'span': 'USB ports',
  'label': 'neutral'},
 {'text': 'It has so much more speed and the screen is very sharp.',
  'span': 'speed',
  'label': 'positive'},
 {'text': 'It has so much more speed and the screen is very sharp.',
  'span': 'screen',
  'label': 'positive'},
 {'text': 'Everything I wanted and everything I needed and the price was great!',
  'span': 'price',
  'label': 'positive'},
 {'text': "It's not inexpensive but the Hardware performance is impressive for a computer this small.",
  'span': 'Hardware performance',
  'label': 'positive'},
 {'text': 'This thing is awesome, everything always works, everything is always easy to set up, everything is compatible, its literally everything I could ask for.',
  'span': 'works',
  'label': 'positive'},
 {'text': 'This thing is awesome, everything always works, everything is always easy to set up, everything is compatible, its literally everything I could ask for.',
  'span': 'set up',
  'label': 'positive'},
 {'text': 'Keyboard responds well to presses.',
  'span': 'Keyboard',
  'label': 'positive'},
 {'text': 'Lastly, Windows 8 is annoying.',
  'span': 'Windows 8',
  'label': 'negative'},
 {'text': 'Everything is so easy and intuitive to setup or configure.',
  'span': 'setup',
  'label': 'positive'},
 {'text': 'Everything is so easy and intuitive to setup or configure.',
  'span': 'configure',
  'label': 'positive'},
 {'text': 'Biggest complaint is Windows 8 .',
  'span': 'Windows 8',
  'label': 'negative'},
 {'text': 'Only 2 usb ports...seems kind of...limited.',
  'span': 'usb ports',
  'label': 'negative'},
 {'text': 'It has all the expected features and more +plus a wide screen and more than roomy keyboard.',
  'span': 'features',
  'label': 'positive'},
 {'text': 'It has all the expected features and more +plus a wide screen and more than roomy keyboard.',
  'span': 'screen',
  'label': 'positive'},
 {'text': 'It has all the expected features and more +plus a wide screen and more than roomy keyboard.',
  'span': 'keyboard',
  'label': 'positive'},
 {'text': 'Amazing Performance for anything I throw at it.',
  'span': 'Performance',
  'label': 'positive'},
 {'text': 'The receiver was full of superlatives for the quality and performance.',
  'span': 'quality',
  'label': 'positive'},
 {'text': 'The receiver was full of superlatives for the quality and performance.',
  'span': 'performance',
  'label': 'positive'},
 {'text': 'I was extremely happy with the OS itself.',
  'span': 'OS',
  'label': 'positive'},
 {'text': 'The new MBP offers great portability and gives us confidence that we are not going to need to purchase a new laptop in 18 months.',
  'span': 'portability',
  'label': 'positive'},
 {'text': "The criticism has waned, and now I'd be the first to recommend an Air for truly portable computing.",
  'span': 'portable computing',
  'label': 'positive'},
 {'text': 'I would have given it 5 starts was it not for the fact that it had Windows 8',
  'span': 'Windows 8',
  'label': 'negative'},
 {'text': 'MS Office 2011 for Mac is wonderful, well worth it.',
  'span': 'MS Office 2011 for Mac',
  'label': 'positive'},
 {'text': 'But the performance of Mac Mini is a huge disappointment.',
  'span': 'performance',
  'label': 'negative'},
 {'text': "They don't just look good; they deliver excellent performance.",
  'span': 'look',
  'label': 'positive'},
 {'text': "They don't just look good; they deliver excellent performance.",
  'span': 'performance',
  'label': 'positive'},
 {'text': 'I have had it over a year now with out a Glitch of any kind..I love the lit up keys and screen display...this thing is Fast and clear as can be.',
  'span': 'lit up keys',
  'label': 'positive'},
 {'text': 'I have had it over a year now with out a Glitch of any kind..I love the lit up keys and screen display...this thing is Fast and clear as can be.',
  'span': 'screen display',
  'label': 'positive'},
 {'text': 'The Mountain Lion OS is not hard to figure out if you are familiar with Microsoft Windows.',
  'span': 'Mountain Lion OS',
  'label': 'neutral'},
 {'text': 'The Mountain Lion OS is not hard to figure out if you are familiar with Microsoft Windows.',
  'span': 'Microsoft Windows',
  'label': 'neutral'},
 {'text': 'However, I can refute that OSX is "FAST".',
  'span': 'OSX',
  'label': 'negative'},
 {'text': 'Enjoy using Microsoft Office!',
  'span': 'Microsoft Office',
  'label': 'positive'},
 {'text': 'Incredible graphics and brilliant colors.',
  'span': 'graphics',
  'label': 'positive'},
 {'text': 'Incredible graphics and brilliant colors.',
  'span': 'colors',
  'label': 'positive'},
 {'text': 'Built-in apps are purely amazing.',
  'span': 'Built-in apps',
  'label': 'positive'},
 {'text': 'Cons: Screen resolution.',
  'span': 'Screen resolution',
  'label': 'neutral'},
 {'text': 'From the speed to the multi touch gestures this operating system beats Windows easily.',
  'span': 'operating system',
  'label': 'positive'},
 {'text': 'From the speed to the multi touch gestures this operating system beats Windows easily.',
  'span': 'Windows',
  'label': 'neutral'},
 {'text': 'From the speed to the multi touch gestures this operating system beats Windows easily.',
  'span': 'speed',
  'label': 'neutral'},
 {'text': 'From the speed to the multi touch gestures this operating system beats Windows easily.',
  'span': 'multi touch gestures',
  'label': 'neutral'},
 {'text': "I really like the size and I'm a fan of the ACERS.",
  'span': 'size',
  'label': 'positive'},
 {'text': 'I opted for the SquareTrade 3-Year Computer Accidental Protection Warranty ($1500-2000) which also support "accidents" like drops and spills that are NOT covered by AppleCare.',
  'span': 'SquareTrade 3-Year Computer Accidental Protection Warranty',
  'label': 'negative'},
 {'text': 'I opted for the SquareTrade 3-Year Computer Accidental Protection Warranty ($1500-2000) which also support "accidents" like drops and spills that are NOT covered by AppleCare.',
  'span': 'AppleCare',
  'label': 'negative'},
 {'text': "It's light and easy to transport.",
  'span': 'transport',
  'label': 'positive'},
 {'text': 'Once you get past learning how to use the poorly designed Windows 8 Set-Up you may feel frustrated.',
  'span': 'Windows 8 Set-Up',
  'label': 'negative'},
 {'text': "It's been time for a new laptop, and the only debate was which size of the Mac laptops, and whether to spring for the retina display.",
  'span': 'size',
  'label': 'neutral'},
 {'text': "It's been time for a new laptop, and the only debate was which size of the Mac laptops, and whether to spring for the retina display.",
  'span': 'retina display',
  'label': 'neutral'},
 {'text': 'The reason why I choose apple MacBook because of their design and the aluminum casing.',
  'span': 'design',
  'label': 'neutral'},
 {'text': 'The reason why I choose apple MacBook because of their design and the aluminum casing.',
  'span': 'aluminum casing',
  'label': 'neutral'},
 {'text': 'The aluminum body sure makes it stand out.',
  'span': 'aluminum body',
  'label': 'neutral'},
 {'text': 'It is very easy to integrate bluetooth devices, and USB devices are recognized almost instantly.',
  'span': 'integrate bluetooth devices',
  'label': 'positive'},
 {'text': 'It is very easy to integrate bluetooth devices, and USB devices are recognized almost instantly.',
  'span': 'USB devices',
  'label': 'positive'},
 {'text': 'And the fact that Apple is driving the 13" RMBP with the Intel4000 graphic chip seems underpowered (to me.',
  'span': 'Intel4000 graphic chip',
  'label': 'negative'},
 {'text': 'Apple removed the DVD drive Firewire port (will work with adapter) and put the SDXC slot in a silly position on the back.',
  'span': 'DVD drive Firewire port',
  'label': 'negative'},
 {'text': 'Apple removed the DVD drive Firewire port (will work with adapter) and put the SDXC slot in a silly position on the back.',
  'span': 'adapter',
  'label': 'negative'},
 {'text': 'Apple removed the DVD drive Firewire port (will work with adapter) and put the SDXC slot in a silly position on the back.',
  'span': 'SDXC slot',
  'label': 'negative'},
 {'text': 'The durability of the laptop will make it worth the money.',
  'span': 'durability',
  'label': 'positive'},
 {'text': 'Well designed and fast.', 'span': 'designed', 'label': 'positive'},
 {'text': 'But I was completely wrong, this computer is UNBELIEVABLE amazing and easy to use.',
  'span': 'use',
  'label': 'positive'},
 {'text': 'Exactly as posted plus a great value.',
  'span': 'value',
  'label': 'positive'},
 {'text': 'The specs are pretty good too.',
  'span': 'specs',
  'label': 'positive'},
 {'text': 'Apple is unmatched in product quality,aesthetics,craftmanship, and customer service.',
  'span': 'product quality',
  'label': 'positive'},
 {'text': 'Apple is unmatched in product quality,aesthetics,craftmanship, and customer service.',
  'span': 'aesthetics',
  'label': 'positive'},
 {'text': 'Apple is unmatched in product quality,aesthetics,craftmanship, and customer service.',
  'span': 'craftmanship',
  'label': 'positive'},
 {'text': 'Apple is unmatched in product quality,aesthetics,craftmanship, and customer service.',
  'span': 'customer service',
  'label': 'positive'},
 {'text': 'It is a great size and amazing windows 8 included!',
  'span': 'size',
  'label': 'positive'},
 {'text': 'It is a great size and amazing windows 8 included!',
  'span': 'windows 8',
  'label': 'positive'},
 {'text': 'I do not like too much Windows 8.',
  'span': 'Windows 8',
  'label': 'negative'},
 {'text': 'Startup times are incredibly long: over two minutes.',
  'span': 'Startup times',
  'label': 'negative'},
 {'text': 'Also stunning colors and speedy',
  'span': 'colors',
  'label': 'positive'},
 {'text': 'great price free shipping what else can i ask for!!',
  'span': 'price',
  'label': 'positive'},
 {'text': 'great price free shipping what else can i ask for!!',
  'span': 'shipping',
  'label': 'positive'},
 {'text': 'This mouse is terrific.', 'span': 'mouse', 'label': 'positive'},
 {'text': 'It is really thick around the battery.',
  'span': 'battery',
  'label': 'neutral'},
 {'text': 'And windows 7 works like a charm.',
  'span': 'windows 7',
  'label': 'positive'},
 {'text': ':) Great product, great price, great delivery, and great service.',
  'span': 'price',
  'label': 'positive'},
 {'text': ':) Great product, great price, great delivery, and great service.',
  'span': 'delivery',
  'label': 'positive'},
 {'text': ':) Great product, great price, great delivery, and great service.',
  'span': 'service',
  'label': 'positive'},
 {'text': ':] It arrived so fast and customer service was great.',
  'span': 'customer service',
  'label': 'positive'},
 {'text': 'tried windows 8 and hated it !!!',
  'span': 'windows 8',
  'label': 'negative'},
 {'text': 'The price is higher than most lab top out there; however, he/she will get what they paid for, which is a great computer.',
  'span': 'price',
  'label': 'negative'},
 {'text': 'Set up was a breeze.', 'span': 'Set up', 'label': 'positive'},
 {'text': 'But I do NOT like Win8.', 'span': 'Win8', 'label': 'negative'},
 {'text': 'I am still in the process of learning about its features.',
  'span': 'features',
  'label': 'neutral'},
 {'text': 'I had the same reasons as most PC users: the price, the overbearing restrictions of OSX and lack of support for games.',
  'span': 'price',
  'label': 'negative'},
 {'text': 'I had the same reasons as most PC users: the price, the overbearing restrictions of OSX and lack of support for games.',
  'span': 'OSX',
  'label': 'negative'},
 {'text': 'I had the same reasons as most PC users: the price, the overbearing restrictions of OSX and lack of support for games.',
  'span': 'support for games',
  'label': 'negative'},
 {'text': "I wanted it for it's mobility and man, this little bad boy is very nice.",
  'span': 'mobility',
  'label': 'positive'},
 {'text': 'The investment of a new MacBook Pro came at a price, but totally worth it for a good piece of mind.',
  'span': 'price',
  'label': 'positive'},
 {'text': 'I found the mini to be:Exceptionally easy to set up',
  'span': 'set up',
  'label': 'positive'},
 {'text': 'Having USB3 is why I bought this Mini.',
  'span': 'USB3',
  'label': 'neutral'},
 {'text': "The sound is nice and loud; I don't have any problems with hearing anything.",
  'span': 'sound',
  'label': 'positive'},
 {'text': 'It is very slim, the track pad is very much impressed with me.',
  'span': 'track pad',
  'label': 'neutral'},
 {'text': 'The settings are not user-friendly either.',
  'span': 'settings',
  'label': 'negative'},
 {'text': 'Thank goodness for OpenOffice!',
  'span': 'OpenOffice',
  'label': 'positive'},
 {'text': 'Awesome form factor, great battery life, wonderful UX.',
  'span': 'form factor',
  'label': 'positive'},
 {'text': 'Awesome form factor, great battery life, wonderful UX.',
  'span': 'battery life',
  'label': 'positive'},
 {'text': 'Awesome form factor, great battery life, wonderful UX.',
  'span': 'UX',
  'label': 'positive'},
 {'text': 'i love the keyboard and the screen.',
  'span': 'keyboard',
  'label': 'positive'},
 {'text': 'i love the keyboard and the screen.',
  'span': 'screen',
  'label': 'positive'},
 {'text': 'However, there are MAJOR issues with the touchpad which render the device nearly useless.',
  'span': 'touchpad',
  'label': 'negative'},
 {'text': "I've already upgraded o Mavericks and I am impressed with everything about this computer.",
  'span': 'Mavericks',
  'label': 'neutral'},
 {'text': 'Not as fast as I would have expect for an i5.',
  'span': 'i5',
  'label': 'neutral'},
 {'text': 'thanks for great service and shipping!',
  'span': 'service',
  'label': 'positive'},
 {'text': 'thanks for great service and shipping!',
  'span': 'shipping',
  'label': 'positive'},
 {'text': 'The performance seems quite good, and built-in applications like iPhoto work great with my phone and camera.',
  'span': 'performance',
  'label': 'positive'},
 {'text': 'The performance seems quite good, and built-in applications like iPhoto work great with my phone and camera.',
  'span': 'built-in applications',
  'label': 'positive'},
 {'text': 'The performance seems quite good, and built-in applications like iPhoto work great with my phone and camera.',
  'span': 'iPhoto',
  'label': 'positive'},
 {'text': 'I did swap out the hard drive for a Samsung 830 SSD which I highly recommend.',
  'span': 'hard drive',
  'label': 'negative'},
 {'text': 'I did swap out the hard drive for a Samsung 830 SSD which I highly recommend.',
  'span': 'Samsung 830 SSD',
  'label': 'positive'},
 {'text': 'Starts up in a hurry and everything is ready to go.',
  'span': 'Starts up',
  'label': 'neutral'},
 {'text': "Yes, that's a good thing, but it's made from aluminum that scratches easily.",
  'span': 'aluminum',
  'label': 'negative'},
 {'text': 'Quick and has built in virus control.',
  'span': 'built in virus control',
  'label': 'positive'},
 {'text': 'Took a long time trying to decide between one with retina display and one without.',
  'span': 'retina display',
  'label': 'neutral'},
 {'text': 'I was also informed that the components of the Mac Book were dirty.',
  'span': 'components',
  'label': 'neutral'},
 {'text': "the hardware problems have been so bad, i can't wait till it completely dies in 3 years, TOPS!",
  'span': 'hardware',

In [ ]:
import torch
from transformers import T5TokenizerFast, AutoModelForSeq2SeqLM

tokenizer = T5TokenizerFast.from_pretrained("whismyswift/t5-absa-2")
model = AutoModelForSeq2SeqLM.from_pretrained("whismyswift/t5-absa-2")
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

Loading weights:   0%|          | 0/131 [00:00<?, ?it/s]

In [ ]:
def extract_aspects_and_sentiment(text, model, tokenizer, device, num_beams=4, max_target_length=64):
    model.eval()

    # Updated prefix to match training
    input_text = f"extract aspect and sentiment: {text}"
    inputs = tokenizer(
        input_text,
        return_tensors="pt",
        max_length=128,
        truncation=True,
    ).to(device)

    with torch.no_grad():
        outputs = model.generate(
            inputs["input_ids"],
            attention_mask=inputs["attention_mask"],
            max_length=max_target_length,
            num_beams=num_beams,
            early_stopping=True,
        )

    raw_output = tokenizer.decode(outputs[0], skip_special_tokens=True).strip()

    # Parse the output: "battery life | positive"
    if "|" in raw_output:
        aspect, sentiment = raw_output.split("|", 1)
        aspect = aspect.strip()
        sentiment = sentiment.strip()
    else:
        # Fallback if model doesn't produce expected format
        aspect = raw_output
        sentiment = "unknown"

    return {"aspect": aspect, "sentiment": sentiment, "raw": raw_output}

In [ ]:
test = dataset[3]
text = test['text']
label = test['span']
result = extract_aspects_and_sentiment(text, model, tokenizer, device)
print(text)
print(label)
print(result)

Did not enjoy the new Windows 8 and touchscreen functions.
Windows 8
{'aspect': 'touchscreen functions', 'sentiment': 'negative', 'raw': 'touchscreen functions | negative'}

In [ ]:
from tqdm.auto import tqdm

correct_aspect_matches = 0
correct_sentiment_given_aspect = 0
total_samples = len(dataset)

predictions_t5 = []

for item in tqdm(dataset, desc="Evaluating T5 model"):
    text = item['text']
    true_aspect = item['span']
    true_sentiment = item['label']

    # Get model prediction
    predicted_result = extract_aspects_and_sentiment(text, model, tokenizer, device)
    predicted_aspect = predicted_result['aspect']
    predicted_sentiment = predicted_result['sentiment']

    # Store predictions
    predictions_t5.append({
        "original_text": text,
        "original_span": true_aspect,
        "original_label": true_sentiment,
        "predicted_aspect": predicted_aspect,
        "predicted_sentiment": predicted_sentiment,
        "raw_output": predicted_result['raw']
    })

    # Evaluate aspect extraction
    if predicted_aspect.lower() == true_aspect.lower():
        correct_aspect_matches += 1
        # Evaluate sentiment prediction only if aspect is correct
        if predicted_sentiment.lower() == true_sentiment.lower():
            correct_sentiment_given_aspect += 1

# Calculate metrics
aspect_accuracy = correct_aspect_matches / total_samples
sentiment_accuracy_given_aspect = correct_sentiment_given_aspect / correct_aspect_matches if correct_aspect_matches > 0 else 0

print(f"\n--- T5 Model Performance on Test Set ---")
print(f"Total Samples: {total_samples}")
print(f"Correct Aspect Matches: {correct_aspect_matches}")
print(f"Aspect Extraction Accuracy: {aspect_accuracy:.4f}")
print(f"Correct Sentiment (given correct aspect): {correct_sentiment_given_aspect}")
print(f"Sentiment Accuracy (conditional on correct aspect): {sentiment_accuracy_given_aspect:.4f}")

# Optionally, save the predictions to a file
output_predictions_file_t5 = "t5_test_predictions.json"
with open(output_predictions_file_t5, 'w') as f:
    json.dump(predictions_t5, f, indent=4)

print(f"T5 predictions saved to {output_predictions_file_t5}")

# Display a few examples
print("\n--- T5 Predictions Examples ---")
for i, pred_item in enumerate(predictions_t5[:5]):
    print(f"Example {i+1}:")
    print(f"  Text: {pred_item['original_text']}")
    print(f"  Original Span: {pred_item['original_span']}, Label: {pred_item['original_label']}")
    print(f"  Predicted Aspect: {pred_item['predicted_aspect']}, Sentiment: {pred_item['predicted_sentiment']}")
    print(f"  Raw Output: {pred_item['raw_output']}")
    print("-" * 30)

Evaluating T5 model:   0%|          | 0/651 [00:00<?, ?it/s]

--- T5 Model Performance on Test Set ---
Total Samples: 651
Correct Aspect Matches: 353
Aspect Extraction Accuracy: 0.5422
Correct Sentiment (given correct aspect): 212
Sentiment Accuracy (conditional on correct aspect): 0.6006
T5 predictions saved to t5_test_predictions.json

--- T5 Predictions Examples ---
Example 1:
  Text: Boot time is super fast, around anywhere from 35 seconds to 1 minute.
  Original Span: Boot time, Label: positive
  Predicted Aspect: Boot time, Sentiment: positive
  Raw Output: Boot time | positive
------------------------------
Example 2:
  Text: tech support would not fix the problem unless I bought your plan for $150 plus.
  Original Span: tech support, Label: negative
  Predicted Aspect: tech support, Sentiment: negative
  Raw Output: tech support | negative
------------------------------
Example 3:
  Text: Set up was easy.
  Original Span: Set up, Label: positive
  Predicted Aspect: Set up, Sentiment: positive
  Raw Output: Set up | positive
------------------------------
Example 4:
  Text: Did not enjoy the new Windows 8 and touchscreen functions.
  Original Span: Windows 8, Label: negative
  Predicted Aspect: touchscreen functions, Sentiment: negative
  Raw Output: touchscreen functions | negative
------------------------------
Example 5:
  Text: Did not enjoy the new Windows 8 and touchscreen functions.
  Original Span: touchscreen functions, Label: negative
  Predicted Aspect: touchscreen functions, Sentiment: negative
  Raw Output: touchscreen functions | negative
------------------------------

## Testing with basic T5

In [ ]:
import torch
from transformers import T5TokenizerFast, AutoModelForSeq2SeqLM
from tqdm.auto import tqdm
import json

basic_t5_tokenizer = T5TokenizerFast.from_pretrained("t5-small")
basic_t5_model = AutoModelForSeq2SeqLM.from_pretrained("t5-small")
basic_t5_device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
basic_t5_model = basic_t5_model.to(basic_t5_device)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json: 0.00B [00:00, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/131 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

In [ ]:
correct_aspect_matches_basic_t5 = 0
correct_sentiment_given_aspect_basic_t5 = 0
total_samples_basic_t5 = len(dataset)

predictions_basic_t5 = []

print(f"Evaluating basic T5 model on {total_samples_basic_t5} samples...")
for item in tqdm(dataset, desc="Evaluating Basic T5 model"):
    text = item['text']
    true_aspect = item['span']
    true_sentiment = item['label']

    # Get model prediction using the reusable function
    predicted_result = extract_aspects_and_sentiment(text, basic_t5_model, basic_t5_tokenizer, basic_t5_device)
    predicted_aspect = predicted_result['aspect']
    predicted_sentiment = predicted_result['sentiment']

    # Store predictions
    predictions_basic_t5.append({
        "original_text": text,
        "original_span": true_aspect,
        "original_label": true_sentiment,
        "predicted_aspect": predicted_aspect,
        "predicted_sentiment": predicted_sentiment,
        "raw_output": predicted_result['raw']
    })

    # Evaluate aspect extraction
    if predicted_aspect.lower() == true_aspect.lower():
        correct_aspect_matches_basic_t5 += 1
        # Evaluate sentiment prediction only if aspect is correct
        if predicted_sentiment.lower() == true_sentiment.lower():
            correct_sentiment_given_aspect_basic_t5 += 1

# Calculate metrics
aspect_accuracy_basic_t5 = correct_aspect_matches_basic_t5 / total_samples_basic_t5
sentiment_accuracy_given_aspect_basic_t5 = correct_sentiment_given_aspect_basic_t5 / correct_aspect_matches_basic_t5 if correct_aspect_matches_basic_t5 > 0 else 0

print(f"\n--- Basic T5 Model Performance on Test Set ---")
print(f"Total Samples: {total_samples_basic_t5}")
print(f"Correct Aspect Matches: {correct_aspect_matches_basic_t5}")
print(f"Aspect Extraction Accuracy: {aspect_accuracy_basic_t5:.4f}")
print(f"Correct Sentiment (given correct aspect): {correct_sentiment_given_aspect_basic_t5}")
print(f"Sentiment Accuracy (conditional on correct aspect): {sentiment_accuracy_given_aspect_basic_t5:.4f}")

print("\n--- Basic T5 Predictions Examples ---")
for i, pred_item in enumerate(predictions_basic_t5[:5]):
    print(f"Example {i+1}:")
    print(f"  Text: {pred_item['original_text']}")
    print(f"  Original Span: {pred_item['original_span']}, Label: {pred_item['original_label']}")
    print(f"  Predicted Aspect: {pred_item['predicted_aspect']}, Sentiment: {pred_item['predicted_sentiment']}")
    print(f"  Raw Output: {pred_item['raw_output']}")
    print("-" * 30)

Evaluating basic T5 model on 651 samples...

Evaluating Basic T5 model:   0%|          | 0/651 [00:00<?, ?it/s]

--- Basic T5 Model Performance on Test Set ---
Total Samples: 651
Correct Aspect Matches: 0
Aspect Extraction Accuracy: 0.0000
Correct Sentiment (given correct aspect): 0
Sentiment Accuracy (conditional on correct aspect): 0.0000
Basic T5 predictions saved to basic_t5_test_predictions.json

--- Basic T5 Predictions Examples ---
Example 1:
  Text: Boot time is super fast, around anywhere from 35 seconds to 1 minute.
  Original Span: Boot time, Label: positive
  Predicted Aspect: aspect and sentiment: Boot time is super fast, anywhere from 35 seconds to 1 minute., Sentiment: unknown
  Raw Output: aspect and sentiment: Boot time is super fast, anywhere from 35 seconds to 1 minute.
------------------------------
Example 2:
  Text: tech support would not fix the problem unless I bought your plan for $150 plus.
  Original Span: tech support, Label: negative
  Predicted Aspect: aspect and sentiment: tech support would not fix the problem unless I bought your plan for $150 plus., Sentiment: unknown
  Raw Output: aspect and sentiment: tech support would not fix the problem unless I bought your plan for $150 plus.
------------------------------
Example 3:
  Text: Set up was easy.
  Original Span: Set up, Label: positive
  Predicted Aspect: extract aspect and sentiment: Set up was easy., Sentiment: unknown
  Raw Output: extract aspect and sentiment: Set up was easy.
------------------------------
Example 4:
  Text: Did not enjoy the new Windows 8 and touchscreen functions.
  Original Span: Windows 8, Label: negative
  Predicted Aspect: .., Sentiment: unknown
  Raw Output: ..
------------------------------
Example 5:
  Text: Did not enjoy the new Windows 8 and touchscreen functions.
  Original Span: touchscreen functions, Label: negative
  Predicted Aspect: .., Sentiment: unknown
  Raw Output: ..
------------------------------